services:
  - type: web
    name: leetforce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn multi_model_chat:app --host 0.0.0.0 --port 8000
    plan: free
